### ISSUE TITLE
CohortCount.csv generation - bug fix 

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/StudyProtocols#15]
The settings file that allows generation of several cohort using atlas ID is great.
I used that for a cancer study referenced here
http://forums.ohdsi.org/t/how-to-do-quick-feasibility-counts-from-r-given-public-server-cohort-definition-url-link/2831/3?u=vojtech_huser

It worked fine for 1 cohort.

With two cohorts, I was getting always only one cohort back.
I found a bug in the code:

On this line

https://github.com/OHDSI/StudyProtocols/blob/master/AlendronateVsRaloxifene/R/CreateCohorts.R#L79

part of code that has [i] must be removed.

bad code (current)
counts <- merge(counts, data.frame(cohortDefinitionId = cohortsToCreate$cohortId[i],
                                     cohortName  = cohortsToCreate$name[i]))

good code (fixed)
counts <- merge(counts, data.frame(cohortDefinitionId = cohortsToCreate$cohortId,
                                     cohortName  = cohortsToCreate$name))

**Comment by schuemie** [comment]
Thanks Vojtech!

I just fixed it both [here](https://github.com/OHDSI/StudyProtocols/commit/c2bc8cebe7b72f5acc0c2fd49d118dab1efccdfb) and in [OhdsiRTools](https://github.com/OHDSI/OhdsiRTools/commit/003fdfb9827cee6c5a51dea8874da5419bd53872).
