### ISSUE TITLE
Study 1 - Treatment Pathways - Version 2 minCellCount 2 - Postgres - sql code issues

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/StudyProtocols#2]
Greetings,

It seems like the SQL code got a bit garbled up between lines 2500 and 2550 (roughly, it changes depending on Depression, HTN or T2DM SQL files.  Some of the statements are throwing errors when I try to execute them AS-IS.  I am attaching my fixed version of the files which I fixed using adapting the SQL code found on the MSSQL server version of the files. I successfully ran these files on my Postgres server and calculates the basic summary counts perfectly. Overall, the issue is with the first step of the attrition tables (0.  count total persons for attrition table). This might also be found in the Version 2 minCellCount 1 files which I haven't looked at yet. 

This seems to be an issue with the Oracle version of the files as well (I haven't checked the other ones) and only the MSSQL server ones seem to be complete. Was the code translated using some kind of automated software package? 

Dropbox link to fixed files: 

https://dl.dropboxusercontent.com/u/21004832/Study1-V2-MC2-fixedfiles.zip

**Comment by cgreich** [comment]
Juan:

All the translations happen through the SQLRender (missing another "er" at the end of the word. :smirk: ) - see https://github.com/OHDSI/SQLRender. Please help debugging it. It is crude, but the main advantage of it is that Martijn just built it, which is 1000 times better than a perfect one that only exists in our dreams.

**Comment by jmbanda** [comment]
Hello,

I was using the direct postgre sql files, but when using sqlrender on Jon
Duke's study 2 it worked like a charm. I will use the R script for when we
re-run the analysis once we add our text data. Thanks for looking into the
issue.

**Comment by jduke99** [comment]
Juan,

Given the extra risk of error in updating all SQL versions in concert with the R version, I've gone ahead and removed the SQL folder to encourage use of the R version (as Patrick has recommended the outset). It also keeps it consistent with Study #2 and pending CohortMethod based studies. I have added an update to the readme for those wishing to run directly via SQL.

Thanks,
Jon
