### ISSUE TITLE
Error when Generating outcomes (package AlendronateVsRaloxifene)

### ISSUE THREAD

**Issue by jepark315** [OHDSI/StudyProtocols#23]
Hello,
I'm interested in this study but getting some errors running it.

`Warning : the condition has length>1 and only the first element will be used`
This warning doesn't look so probelmatic.
There were three chunks of error messages below.
I wonder if this is because I'm using Parallellogger of version 1.0.1 so I'm gonna update and run this package again but please tell me if you know what caused this issue.
Or I suspect that this error is caused becasue my institution hasn't converted some concepts.

`Thread 1 returns error : "cannot oppen the connection" when using argument(s) : list(exposureID = NA, outcomeID = NA, modelFolder= NA, covarFileName = c("E:/DPJE001/Desktop/study_results/positiveControlSynthesis/CovarsForModel_gNA", .."`
`Thread 2 returns error : "argument is of length 0 when using argument(s) : list(exposureID = integer(0), outcomeID = integer(0), modelFolder= character(0), covarFileName = "E:/DPJE001/Desktop/study_results/positiveControlSynthesis/CovarsForModel_g"_, list(exposureID= c(99321,...,)"`
`Error in ParallelLogger:clusterapply(cluster,tasks,generateOutcomes, : 
 Error(s) when calling function 'fun', see earlier messages for details`

**Comment by jepark315** [comment]
Well, I opened Cohortcount.csv and there were only 4 population in VertebralFracture. so maybe this is what caused the error...?

**Comment by jepark315** [comment]
I think I know why. There's no such file. "E:/DPJE001/Desktop/study_results/positiveControlSynthesis/CovarsForModel_gNA" But why isn't it created? What could be the cause?

**Comment by schuemie** [comment]
The most likely cause is low (or zero) counts for the exposures and / or outcomes (both outcomes of interest and negative control outcomes).

As a rule of thumb, in CohortCounts.csv the Alendronate and Raloxifene cohorts should each have count > 2,500, and at least some of the negative controls should have count > 1000. Do you see that for your database?

**Comment by jepark315** [comment]
There are far less counts in the cohorts.  Less than 500 counts for the Alendronate and Raloxifene cohorts. so is it causing the errors?

**Comment by schuemie** [comment]
Yes, I'm afraid it is. You really need a larger population to run this study.

**Comment by jepark315** [comment]
Thank you very much for reply :)
